"""Backward-compatible student handler facade.

Re-exports routers and handler functions from the modular `bot.student.handlers` package
to maintain 100% backward compatibility for existing references and test suites.
"""

from bot.student.handlers import student_router
from bot.student.handlers.feedback import (
    feedback_router,
    process_feedback_comment_message,
    process_feedback_skip_comment,
    process_rating_selection,
    prompt_feedback_rating,
)
from bot.student.handlers.profile import (
    process_profile_hall_edit,
    process_profile_phone_edit,
    profile_edit_phone,
    profile_router,
    profile_set_hall,
    show_profile,
)
from bot.student.handlers.registration import (
    _review_keyboard,
    _show_review_screen,
    cancel_registration,
    edit_full_name,
    edit_phone,
    receive_full_name,
    receive_phone,
    registration_router,
    select_hall,
    submit_registration,
)
from bot.student.handlers.requests import (
    _format_request_detail,
    _req_step_prompt,
    _show_request_review,
    cancel_request_creation,
    confirm_cancel_request,
    confirm_request_update,
    edit_request_field,
    my_requests_page_callback,
    noop_callback,
    process_dropoff_address,
    process_dropoff_landmark,
    process_edit_date_callback,
    process_edit_hall_callback,
    process_edit_size_callback,
    process_edit_time_callback,
    process_edit_value_message,
    process_hall_select,
    process_luggage_count,
    process_luggage_size,
    process_pickup_detail,
    process_preferred_date_callback,
    process_preferred_date_message,
    process_recipient_name,
    process_recipient_phone,
    process_special_instructions,
    process_time_window_callback,
    process_time_window_message,
    prompt_cancel_request,
    requests_router,
    select_field_to_edit,
    show_my_requests_list,
    show_request_detail,
    skip_dropoff_landmark,
    skip_special_instructions,
    start_request_creation,
    start_request_edit,
    submit_request_creation,
)
from bot.student.service import register_student

__all__ = [
    "student_router",
    "registration_router",
    "requests_router",
    "profile_router",
    "feedback_router",
    "register_student",
    "cancel_registration",
    "receive_full_name",
    "select_hall",
    "receive_phone",
    "edit_full_name",
    "edit_phone",
    "submit_registration",
    "start_request_creation",
    "cancel_request_creation",
    "process_pickup_detail",
    "process_dropoff_address",
    "process_dropoff_landmark",
    "skip_dropoff_landmark",
    "process_hall_select",
    "process_recipient_name",
    "process_recipient_phone",
    "process_luggage_size",
    "process_luggage_count",
    "process_preferred_date_callback",
    "process_preferred_date_message",
    "process_time_window_callback",
    "process_time_window_message",
    "skip_special_instructions",
    "process_special_instructions",
    "edit_request_field",
    "submit_request_creation",
    "show_my_requests_list",
    "my_requests_page_callback",
    "show_request_detail",
    "start_request_edit",
    "select_field_to_edit",
    "process_edit_hall_callback",
    "process_edit_size_callback",
    "process_edit_date_callback",
    "process_edit_time_callback",
    "process_edit_value_message",
    "confirm_request_update",
    "prompt_cancel_request",
    "confirm_cancel_request",
    "show_profile",
    "profile_edit_phone",
    "profile_set_hall",
    "process_profile_phone_edit",
    "process_profile_hall_edit",
    "prompt_feedback_rating",
    "process_rating_selection",
    "process_feedback_skip_comment",
    "process_feedback_comment_message",
]