"""test_rev

Revision ID: 162b5aa81caa
Revises: 8df7ae516946
Create Date: 2026-07-24 12:45:05.892660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '162b5aa81caa'
down_revision: Union[str, None] = '8df7ae516946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
