"""test_rev

Revision ID: 2bc320a8ad91
Revises: 9082dd8c65fd
Create Date: 2026-07-23 19:01:36.668386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bc320a8ad91'
down_revision: Union[str, None] = '9082dd8c65fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
