"""test_rev

Revision ID: 34255c883fcb
Revises: 2bc320a8ad91
Create Date: 2026-07-23 19:12:01.472213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34255c883fcb'
down_revision: Union[str, None] = '2bc320a8ad91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
