"""test_rev

Revision ID: 35f013eabe2f
Revises: dd683fe71a4d
Create Date: 2026-07-23 17:03:40.912512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35f013eabe2f'
down_revision: Union[str, None] = 'dd683fe71a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
