"""test_rev

Revision ID: 377e43bd6e01
Revises: af453634a897
Create Date: 2026-07-23 17:38:51.556614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '377e43bd6e01'
down_revision: Union[str, None] = 'af453634a897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
