"""init

Revision ID: 3ec380728795
Revises: 
Create Date: 2026-07-23 16:25:07.229865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ec380728795'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
