"""remove_matric_number

Revision ID: 3f93513f5486
Revises: 9f970db63a4f
Create Date: 2026-07-24 16:58:47.309315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f93513f5486'
down_revision: Union[str, None] = '9f970db63a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_matric_number'), table_name='student_profiles')
    op.drop_column('student_profiles', 'matric_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('matric_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_student_profiles_matric_number'), 'student_profiles', ['matric_number'], unique=True)
    # ### end Alembic commands ###
