"""test_rev

Revision ID: 4a32dca09724
Revises: e32a4190f6e5
Create Date: 2026-07-24 20:45:35.233199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a32dca09724'
down_revision: Union[str, None] = 'e32a4190f6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
