"""test_rev

Revision ID: 52b013592d3e
Revises: 34255c883fcb
Create Date: 2026-07-24 07:38:44.218296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52b013592d3e'
down_revision: Union[str, None] = '34255c883fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
