"""test_rev

Revision ID: 5ea7f18f09f5
Revises: fd078655a0c0
Create Date: 2026-07-24 20:59:37.276759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ea7f18f09f5'
down_revision: Union[str, None] = 'fd078655a0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
