"""test_rev

Revision ID: 6a695af86a3b
Revises: 52b013592d3e
Create Date: 2026-07-24 10:32:46.552243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a695af86a3b'
down_revision: Union[str, None] = '52b013592d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
