"""test_rev

Revision ID: 75918364acc4
Revises: 5ea7f18f09f5
Create Date: 2026-07-24 21:02:58.832075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75918364acc4'
down_revision: Union[str, None] = '5ea7f18f09f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
