"""test_rev

Revision ID: 84a66c2bb3f9
Revises: b2e2b479997f
Create Date: 2026-07-23 17:45:11.377095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84a66c2bb3f9'
down_revision: Union[str, None] = 'b2e2b479997f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
