"""test_rev

Revision ID: 873b53f8741a
Revises: f2c2b75d4b82
Create Date: 2026-07-27 17:52:30.623034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '873b53f8741a'
down_revision: Union[str, None] = 'f2c2b75d4b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
