"""test_rev

Revision ID: 959ef7b8f0d4
Revises: c43cb513e251
Create Date: 2026-07-24 12:59:32.374090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '959ef7b8f0d4'
down_revision: Union[str, None] = 'c43cb513e251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
