"""test_rev

Revision ID: 9f970db63a4f
Revises: 959ef7b8f0d4
Create Date: 2026-07-24 13:02:50.758047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f970db63a4f'
down_revision: Union[str, None] = '959ef7b8f0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
