"""test_rev

Revision ID: af453634a897
Revises: 35f013eabe2f
Create Date: 2026-07-23 17:12:00.789651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af453634a897'
down_revision: Union[str, None] = '35f013eabe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
