"""test_rev

Revision ID: c43cb513e251
Revises: b6f98caafc92
Create Date: 2026-07-24 12:57:13.996094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c43cb513e251'
down_revision: Union[str, None] = 'b6f98caafc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
