"""test_rev

Revision ID: dd683fe71a4d
Revises: f4809bbb9747
Create Date: 2026-07-23 16:33:24.207232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd683fe71a4d'
down_revision: Union[str, None] = 'f4809bbb9747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
