"""test_rev

Revision ID: e32a4190f6e5
Revises: ff178260a449
Create Date: 2026-07-24 20:44:18.137697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e32a4190f6e5'
down_revision: Union[str, None] = 'ff178260a449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
