"""test_rev

Revision ID: f2c2b75d4b82
Revises: fb9443e37abe
Create Date: 2026-07-25 09:29:50.836784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2c2b75d4b82'
down_revision: Union[str, None] = 'fb9443e37abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
