"""test_rev

Revision ID: f4809bbb9747
Revises: 3ec380728795
Create Date: 2026-07-23 16:31:51.125719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4809bbb9747'
down_revision: Union[str, None] = '3ec380728795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
