"""test_rev

Revision ID: fb9443e37abe
Revises: 75918364acc4
Create Date: 2026-07-24 21:04:24.787824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb9443e37abe'
down_revision: Union[str, None] = '75918364acc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
