"""test_rev

Revision ID: fd078655a0c0
Revises: 4a32dca09724
Create Date: 2026-07-24 20:55:21.659681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd078655a0c0'
down_revision: Union[str, None] = '4a32dca09724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
