"""test_rev

Revision ID: ff178260a449
Revises: 3f93513f5486
Create Date: 2026-07-24 20:31:33.065476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff178260a449'
down_revision: Union[str, None] = '3f93513f5486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
