"""Regression tests for the Alembic migration graph (backlog P0 #7).

The repository previously had **two migration heads**
(``a1b2c3d4e5f6`` and ``d773fd78af20``), which makes ``alembic upgrade
head`` fail outright — only an explicit revision id could be applied. On top
of that, 18 of the 24 revision files were autogenerated no-op stubs
(``*_test_rev.py`` with ``def upgrade(): pass``) and
``alembic.ini`` carried the placeholder DSN
``driver://user:pass@localhost/dbname``, which crashed offline mode with
``sqlalchemy.exc.NoSuchModuleError``.

These tests assert the *properties* that make the chain usable, rather than
snapshotting specific revision ids, so that legitimate future migrations do
not break them.

Calls / Depends on:
    - ``alembic.config.Config`` / ``alembic.script.ScriptDirectory`` — read
      the revision graph from ``alembic/`` without touching a database.
    - ``alembic.config.main`` — runs ``upgrade head --sql`` in offline mode to
      assert the whole chain renders to SQL.

Called by:
    - the daily maintenance run (P0 #7).
"""

from __future__ import annotations

import contextlib
import io
import re
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory


REPO_ROOT = Path(__file__).resolve().parents[3]
ALEMBIC_INI = REPO_ROOT / "alembic.ini"
VERSIONS_DIR = REPO_ROOT / "alembic" / "versions"


def _script_directory() -> ScriptDirectory:
    """Build a ScriptDirectory from the repository's alembic config."""
    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    return ScriptDirectory.from_config(cfg)


class TestLinearRevisionGraph:
    """``alembic upgrade head`` only works with exactly one head."""

    def test_has_exactly_one_head(self) -> None:
        """Regression: two heads ('a1b2c3d3d4e5f6', 'd773fd78af20') broke
        ``upgrade head`` with 'Multiple head revisions are present'."""
        heads = _script_directory().get_heads()
        assert len(heads) == 1, f"expected a single head, found {heads}"

    def test_has_exactly_one_base(self) -> None:
        """A single base keeps the chain unambiguous from the bottom up."""
        bases = _script_directory().get_bases()
        assert len(bases) == 1, f"expected a single base, found {bases}"

    def test_every_revision_is_reachable_from_the_head(self) -> None:
        """No orphaned revisions — every file is walked in one pass."""
        revisions = list(_script_directory().walk_revisions())
        assert revisions, "expected at least one migration revision"

        by_id = {rev.revision: rev for rev in revisions}
        seen: set[str] = set()
        for head in _script_directory().get_heads():
            rev = by_id[head]
            while rev is not None:
                if rev.revision in seen:
                    break
                seen.add(rev.revision)
                rev = by_id.get(rev.down_revision) if rev.down_revision else None

        assert seen == set(by_id), (
            "some revisions are not reachable from the head(s): "
            f"{sorted(set(by_id) - seen)}"
        )

    def test_no_dangling_down_revision_references(self) -> None:
        """Every ``down_revision`` must name a file that still exists.

        Deleting the no-op stubs without re-parenting left children pointing
        at removed revisions, which raised ``KeyError`` from Alembic's
        revision map.
        """
        known = {rev.revision for rev in _script_directory().walk_revisions()}
        dangling: list[str] = []
        for rev in _script_directory().walk_revisions():
            if not rev.down_revision:
                continue
            parents = (
                rev.down_revision
                if isinstance(rev.down_revision, (list, tuple))
                else [rev.down_revision]
            )
            for parent in parents:
                if parent not in known:
                    dangling.append(f"{rev.revision} -> {parent}")

        assert not dangling, f"dangling down_revision references: {dangging}"


class TestNoOpStubsRemoved:
    """The 18 autogenerated no-op revisions have been deleted."""

    def test_no_test_rev_stubs_remain(self) -> None:
        stubs = sorted(VERSIONS_DIR.glob("*_test_rev.py"))
        assert not stubs, f"no-op migration stubs still present: {stubs}"

    def test_every_remaining_revision_has_real_operations(self) -> None:
        """Each surviving revision must do something in ``upgrade()``.

        A ``pass``-only ``upgrade()`` is the signature of an autogenerated
        stub that was never edited.
        """
        empty: list[str] = []
        for path in sorted(VERSIONS_DIR.glob("*.py")):
            source = path.read_text(encoding="utf-8")
            body = source.split("def upgrade", 1)[-1].split("def downgrade", 1)[0]
            # Ignore the Alembic boilerplate comment markers.
            body = re.sub(r"#.*", "", body)
            if not body.strip() or not re.search(r"\bop\.", body):
                empty.append(path.name)

        assert not empty, f"revisions with an empty upgrade(): {empty}"


class TestAlembicConfigUrl:
    """``alembic.ini`` must not ship a placeholder DSN."""

    def test_ini_does_not_hardcode_a_dsn(self) -> None:
        """Regression: 'driver://user:pass@localhost/dbname' made
        ``alembic upgrade head --sql`` fail with NoSuchModuleError."""
        ini_text = ALEMBIC_INI.read_text(encoding="utf-8")
        url_match = re.search(
            r"^[ \t]*sqlalchemy\.url[ \t]*=[ \t]*(.*)$", ini_text, flags=re.MULTILINE
        )
        assert url_match is not None, "sqlalchemy.url is missing from alembic.ini"

        configured = url_match.group(1).strip()
        assert configured == "", (
            "alembic.ini must leave sqlalchemy.url empty; the URL is resolved "
            f"at runtime by alembic/env.py. Found: {configured!r}"
        )

    def test_no_placeholder_credentials_in_repo_config(self) -> None:
        """Guard against reintroducing a literal 'user:pass' DSN."""
        offenders = []
        for path in (ALEMBIC_INI, REPO_ROOT / "alembic" / "env.py"):
            if "user:pass" in path.read_text(encoding="utf-8"):
                # A comment naming the old placeholder is acceptable.
                for line in path.read_text(encoding="utf-8").splitlines():
                    stripped = line.strip()
                    if "user:pass" in stripped and not stripped.startswith("#"):
                        offenders.append(f"{path.name}: {stripped}")
                        break
        assert not offenders, f"placeholder credentials found: {offenders}"


class TestOfflineSqlGeneration:
    """``alembic upgrade head --sql`` must render the whole chain."""

    def test_upgrade_head_sql_renders_all_revisions(self) -> None:
        """Regression: offline mode crashed on the placeholder DSN."""
        from alembic import command

        cfg = Config(str(ALEMBIC_INI))
        cfg.set_main_option("script_location", str(REPO_ROOT / "alembic"))
        # Offline rendering must not try to connect to anything.
        cfg.set_main_option("sqlalchemy.url", "postgresql+psycopg2://")

        script = io.StringIO()

        try:
            # ``run_migrations_offline`` calls ``context.configure()`` without
            # an ``output_buffer``, so Alembic's MigrationContext falls back
            # to ``sys.stdout``. Redirect it to capture the rendered SQL.
            with contextlib.redirect_stdout(script):
                command.upgrade(cfg, "head", sql=True)
            rendered = script.getvalue()
        except Exception as exc:  # pragma: no cover - failure path
            pytest.fail(f"offline SQL rendering failed: {exc!r}")

        assert rendered.strip(), "offline mode produced no SQL"

        # Every revision in the chain must appear as a version bump.
        revision_ids = [rev.revision for rev in _script_directory().walk_revisions()]
        for revision_id in revision_ids:
            assert revision_id in rendered, (
                f"revision {revision_id} is missing from the rendered SQL"
            )

    def test_offline_url_resolution_prefers_ini_then_settings(self) -> None:
        """``env._resolve_url`` falls back to app settings, and never
        returns an empty string."""
        import importlib.util

        env_path = REPO_ROOT / "alembic" / "env.py"
        # env.py runs migrations at import time, so only its source-level
        # contract is asserted here (importing it would need a live env).
        source = env_path.read_text(encoding="utf-8")
        assert "def _resolve_url(" in source, "_resolve_url helper is missing"
        assert "RuntimeError" in source, (
            "_resolve_url must raise rather than hand Alembic an empty URL"
        )
        assert importlib.util.find_spec("alembic") is not None